[[actions]]
name = "play"
path = "launcher.exe"

[[actions]]
name = "Play and show private servers"
path = "Dynast.io.exe"
args = ["include-custom", "true"]

[[actions]]
name = "Run Private Server"
path = "run_private.bat"
